# Generated by Django 3.1.3 on 2020-11-17 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('cms_plugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticatedUserPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugins_authenticateduserpluginconfig', serialize=False, to='cms.cmsplugin')),
                ('unauthenticated_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
