# Generated by Django 3.1.3 on 2020-11-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0002_authenticateduserpluginconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticateduserpluginconfig',
            name='show_to',
            field=models.CharField(choices=[('authenticated_users', 'Users who are logged in.'), ('unauthenticated_users', 'Users who are not logged in.')], default='authenticated_users', max_length=100),
        ),
    ]
