# Generated by Django 3.1.3 on 2020-11-19 11:44

from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('cms_plugins', '0003_authenticateduserpluginconfig_show_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlainTextPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugins_plaintextpluginconfig', serialize=False, to='cms.cmsplugin')),
                ('text', models.TextField(blank=True, null=True)),
                ('text_class', models.CharField(blank=True, choices=[('text-primary', 'Primary (blue)'), ('text-secondary', 'Secondary (dark gray)'), ('text-success', 'Success (green)'), ('text-danger', 'Danger (red)'), ('text-warning', 'Warning (yellow)'), ('text-info', 'Info (turquoise)'), ('text-light', 'Light (white)'), ('text-dark', 'Dark (black)'), ('text-body', 'Body (default color)'), ('text-muted', 'Muted (gray)'), ('text-white', 'White'), ('text-black-50', '50% Black'), ('text-white-50', '50% White')], max_length=50, null=True)),
                ('background_class', models.CharField(blank=True, choices=[('bg-primary', 'Primary (blue)'), ('bg-secondary', 'Secondary (dark gray)'), ('bg-success', 'Success (green)'), ('bg-danger', 'Danger (red)'), ('bg-warning', 'Warning (yellow)'), ('bg-info', 'Info (turquoise)'), ('bg-light', 'Light (white)'), ('bg-dark', 'Dark (black)'), ('bg-transparent', 'Transparent'), ('bg-gradient-primary', 'Primary Gradient (blue)'), ('bg-gradient-secondary', 'Secondary Gradient (dark gray)'), ('bg-gradient-success', 'Success Gradient (green)'), ('bg-gradient-danger', 'Danger Gradient (red)'), ('bg-gradient-warning', 'Warning Gradient (yellow)'), ('bg-gradient-info', 'Info Gradient (turquoise)'), ('bg-gradient-light', 'Light Gradient (white)'), ('bg-gradient-dark', 'Dark Gradient (black)')], max_length=50, null=True)),
                ('attributes', djangocms_attributes_field.fields.AttributesField(default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.DeleteModel(
            name='PlainTextPlugin',
        ),
    ]
