# Generated by Django 3.1.3 on 2020-11-17 20:22

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('app_name', models.CharField(blank=True, max_length=200, null=True)),
                ('client_id', models.CharField(blank=True, max_length=200, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=200, null=True)),
                ('limit_by_ip', models.BooleanField(default=False)),
                ('ip_addresses', django_extensions.db.fields.json.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=200, null=True)),
                ('token_type', models.CharField(blank=True, default='Bearer', max_length=50, null=True)),
                ('expires_in', models.IntegerField(default=600, null=True)),
                ('expires_datetime', models.DateTimeField(null=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_auth.application')),
            ],
        ),
    ]
