# Generated by Django 3.1.3 on 2020-11-19 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_description',
            field=models.TextField(blank=True, help_text='This is displayed to all users of your application.', null=True, verbose_name='Application description'),
        ),
        migrations.AddField(
            model_name='application',
            name='homepage_url',
            field=models.URLField(blank=True, help_text='The full URL to your application homepage. (optional)', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_name',
            field=models.CharField(blank=True, help_text='Something users will recognize and trust', max_length=200, null=True, verbose_name='Application Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='client_id',
            field=models.CharField(blank=True, help_text='This value is considered public and can be put into visible configurations.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='client_secret',
            field=models.CharField(blank=True, help_text='Keep this value confidential.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='ip_addresses',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text="A list if ip addresses that can access this endpoint with your credentials. (ex: ['123.45.67.1','123.45.67.2','123.45.67.3'])", null=True),
        ),
        migrations.CreateModel(
            name='ApplicationRedirects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_url', models.URLField(blank=True, null=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_auth.application')),
            ],
        ),
    ]
