# Generated by Django 3.1.3 on 2020-11-24 23:43

from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields
import filer.fields.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('filer', '0012_file_mime_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalBodyPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_modalbodypluginconfig', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ModalCloseButtonPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_modalclosebuttonpluginconfig', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(default='Close', max_length=200)),
                ('button_class', models.CharField(choices=[('btn-primary', 'Primary'), ('btn-secondary', 'Secondary'), ('btn-success', 'Success'), ('btn-danger', 'Danger'), ('btn-warning', 'Warning'), ('btn-info', 'Info'), ('btn-light', 'Light'), ('btn-dark', 'Dark'), ('btn-link', 'Link')], max_length=50, null=True)),
                ('button_size', models.CharField(choices=[('sm', 'Small'), ('lg', 'Large')], max_length=50, null=True)),
                ('additional_css_classes', models.CharField(blank=True, help_text='Space separated. Example: text-right', max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ModalFooterPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_modalfooterpluginconfig', serialize=False, to='cms.cmsplugin')),
                ('additional_css_classes', models.CharField(blank=True, help_text='Space separated. Example: text-right', max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ModalPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_modalpluginconfig', serialize=False, to='cms.cmsplugin')),
                ('target_name', models.CharField(blank=True, max_length=200, null=True)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('static_backdrop', models.BooleanField(default=False, help_text='When backdrop is set to static, the modal will not close when clicking outside it.')),
                ('vertically_centered', models.BooleanField(default=False)),
                ('scrollable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ModalTriggerConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_modaltriggerconfig', serialize=False, to='cms.cmsplugin')),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('trigger_type', models.CharField(choices=[('a', 'Link'), ('button', 'Button')], default='button', max_length=50)),
                ('target', models.CharField(blank=True, max_length=50, null=True)),
                ('button_class', models.CharField(blank=True, choices=[('btn-primary', 'Primary'), ('btn-secondary', 'Secondary'), ('btn-success', 'Success'), ('btn-danger', 'Danger'), ('btn-warning', 'Warning'), ('btn-info', 'Info'), ('btn-light', 'Light'), ('btn-dark', 'Dark'), ('btn-link', 'Link')], max_length=50, null=True)),
                ('button_size', models.CharField(blank=True, choices=[('sm', 'Small'), ('lg', 'Large')], max_length=50, null=True)),
                ('additional_css_classes', models.CharField(blank=True, help_text='Space separated. Example: nav-link text-success', max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NavBarBrandPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_navbarbrandpluginconfig', serialize=False, to='cms.cmsplugin')),
                ('link', models.CharField(blank=True, help_text='URL Name, Page Slug, or external link', max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('target', models.CharField(blank=True, choices=[('_self', 'Same Tab/Window (normal)'), ('_blank', 'New Tab/Window'), ('_parent', 'Parent Frame'), ('_top', 'Full Window (break frames)')], max_length=50, null=True)),
                ('attributes', djangocms_attributes_field.fields.AttributesField(default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NavBarPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_navbarpluginconfig', serialize=False, to='cms.cmsplugin')),
                ('background_class', models.CharField(choices=[('bg-primary', 'Primary (blue)'), ('bg-secondary', 'Secondary (dark gray)'), ('bg-success', 'Success (green)'), ('bg-danger', 'Danger (red)'), ('bg-warning', 'Warning (yellow)'), ('bg-info', 'Info (turquoise)'), ('bg-light', 'Light (white)'), ('bg-dark', 'Dark (black)'), ('bg-transparent', 'Transparent'), ('bg-gradient-primary', 'Primary Gradient (blue)'), ('bg-gradient-secondary', 'Secondary Gradient (dark gray)'), ('bg-gradient-success', 'Success Gradient (green)'), ('bg-gradient-danger', 'Danger Gradient (red)'), ('bg-gradient-warning', 'Warning Gradient (yellow)'), ('bg-gradient-info', 'Info Gradient (turquoise)'), ('bg-gradient-light', 'Light Gradient (white)'), ('bg-gradient-dark', 'Dark Gradient (black)')], default='bg-dark', max_length=50)),
                ('background_scheme', models.CharField(choices=[('navbar-dark', 'Dark Background'), ('navbar-light', 'Light Background')], default='navbar-dark', max_length=50)),
                ('navbar_position', models.CharField(blank=True, choices=[('', 'Normal'), ('fixed-top', 'Fixed top'), ('fixed-bottom', 'Fixed bottom')], default='', max_length=50)),
                ('attributes', djangocms_attributes_field.fields.AttributesField(default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NavDropDownDividerConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_navdropdowndividerconfig', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NavDropDownItemConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_navdropdownitemconfig', serialize=False, to='cms.cmsplugin')),
                ('link', models.CharField(blank=True, help_text='URL Name, Page Slug, or external link', max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('target', models.CharField(blank=True, choices=[('_self', 'Same Tab/Window (normal)'), ('_blank', 'New Tab/Window'), ('_parent', 'Parent Frame'), ('_top', 'Full Window (break frames)')], max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NavDropDownMenuConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_navdropdownmenuconfig', serialize=False, to='cms.cmsplugin')),
                ('text_class', models.CharField(blank=True, choices=[('text-primary', 'Primary (blue)'), ('text-secondary', 'Secondary (dark gray)'), ('text-success', 'Success (green)'), ('text-danger', 'Danger (red)'), ('text-warning', 'Warning (yellow)'), ('text-info', 'Info (turquoise)'), ('text-light', 'Light (white)'), ('text-dark', 'Dark (black)'), ('text-body', 'Body (default color)'), ('text-muted', 'Muted (gray)'), ('text-white', 'White'), ('text-black-50', '50% Black'), ('text-white-50', '50% White')], max_length=50, null=True)),
                ('background_class', models.CharField(blank=True, choices=[('bg-primary', 'Primary (blue)'), ('bg-secondary', 'Secondary (dark gray)'), ('bg-success', 'Success (green)'), ('bg-danger', 'Danger (red)'), ('bg-warning', 'Warning (yellow)'), ('bg-info', 'Info (turquoise)'), ('bg-light', 'Light (white)'), ('bg-dark', 'Dark (black)'), ('bg-transparent', 'Transparent'), ('bg-gradient-primary', 'Primary Gradient (blue)'), ('bg-gradient-secondary', 'Secondary Gradient (dark gray)'), ('bg-gradient-success', 'Success Gradient (green)'), ('bg-gradient-danger', 'Danger Gradient (red)'), ('bg-gradient-warning', 'Warning Gradient (yellow)'), ('bg-gradient-info', 'Info Gradient (turquoise)'), ('bg-gradient-light', 'Light Gradient (white)'), ('bg-gradient-dark', 'Dark Gradient (black)')], max_length=50, null=True)),
                ('attributes', djangocms_attributes_field.fields.AttributesField(default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_navitem', serialize=False, to='cms.cmsplugin')),
                ('dropdown', models.BooleanField(default=False)),
                ('attributes', djangocms_attributes_field.fields.AttributesField(default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NavLinkPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_navlinkpluginconfig', serialize=False, to='cms.cmsplugin')),
                ('link', models.CharField(blank=True, help_text='URL Name, Page Slug, or external link', max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('target', models.CharField(blank=True, choices=[('_self', 'Same Tab/Window (normal)'), ('_blank', 'New Tab/Window'), ('_parent', 'Parent Frame'), ('_top', 'Full Window (break frames)')], max_length=50, null=True)),
                ('text_class', models.CharField(blank=True, choices=[('text-primary', 'Primary (blue)'), ('text-secondary', 'Secondary (dark gray)'), ('text-success', 'Success (green)'), ('text-danger', 'Danger (red)'), ('text-warning', 'Warning (yellow)'), ('text-info', 'Info (turquoise)'), ('text-light', 'Light (white)'), ('text-dark', 'Dark (black)'), ('text-body', 'Body (default color)'), ('text-muted', 'Muted (gray)'), ('text-white', 'White'), ('text-black-50', '50% Black'), ('text-white-50', '50% White')], max_length=50, null=True)),
                ('background_class', models.CharField(blank=True, choices=[('bg-primary', 'Primary (blue)'), ('bg-secondary', 'Secondary (dark gray)'), ('bg-success', 'Success (green)'), ('bg-danger', 'Danger (red)'), ('bg-warning', 'Warning (yellow)'), ('bg-info', 'Info (turquoise)'), ('bg-light', 'Light (white)'), ('bg-dark', 'Dark (black)'), ('bg-transparent', 'Transparent'), ('bg-gradient-primary', 'Primary Gradient (blue)'), ('bg-gradient-secondary', 'Secondary Gradient (dark gray)'), ('bg-gradient-success', 'Success Gradient (green)'), ('bg-gradient-danger', 'Danger Gradient (red)'), ('bg-gradient-warning', 'Warning Gradient (yellow)'), ('bg-gradient-info', 'Info Gradient (turquoise)'), ('bg-gradient-light', 'Light Gradient (white)'), ('bg-gradient-dark', 'Dark Gradient (black)')], max_length=50, null=True)),
                ('dropdown', models.BooleanField(default=False)),
                ('attributes', djangocms_attributes_field.fields.AttributesField(default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NavPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_navpluginconfig', serialize=False, to='cms.cmsplugin')),
                ('style', models.CharField(blank=True, choices=[('', 'Default Nav'), ('nav-tabs', 'Tabs'), ('nav-pills', 'Pills'), ('nav-fill', 'Fill and Justify')], default='', max_length=50)),
                ('background_class', models.CharField(choices=[('bg-primary', 'Primary (blue)'), ('bg-secondary', 'Secondary (dark gray)'), ('bg-success', 'Success (green)'), ('bg-danger', 'Danger (red)'), ('bg-warning', 'Warning (yellow)'), ('bg-info', 'Info (turquoise)'), ('bg-light', 'Light (white)'), ('bg-dark', 'Dark (black)'), ('bg-transparent', 'Transparent'), ('bg-gradient-primary', 'Primary Gradient (blue)'), ('bg-gradient-secondary', 'Secondary Gradient (dark gray)'), ('bg-gradient-success', 'Success Gradient (green)'), ('bg-gradient-danger', 'Danger Gradient (red)'), ('bg-gradient-warning', 'Warning Gradient (yellow)'), ('bg-gradient-info', 'Info Gradient (turquoise)'), ('bg-gradient-light', 'Light Gradient (white)'), ('bg-gradient-dark', 'Dark Gradient (black)')], default='bg-dark', max_length=50)),
                ('horizontal_alignment', models.CharField(choices=[('justify-content-start', 'Left Aligned'), ('justify-content-center', 'Center Aligned'), ('justify-content-end', 'Right Aligned')], default='justify-content-start', max_length=50)),
                ('vertical_desktop', models.BooleanField(default=False)),
                ('vertical_mobile', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HTML5Video',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_html5video', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('aspect_ratio', models.CharField(choices=[('Widescreen 16x9', '16by9'), ('Full/square Screen 4x3', '4by3')], default='Widescreen 16x9', max_length=25)),
                ('attributes', djangocms_attributes_field.fields.AttributesField(default=dict)),
                ('video_file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='html5_video_file', to='filer.file')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
