# Generated by Django 3.1.3 on 2020-11-17 20:21

from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields
import filer.fields.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0012_file_mime_type'),
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavDropDownDividerConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_navdropdowndividerconfig', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NavDropDownItemConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_navdropdownitemconfig', serialize=False, to='cms.cmsplugin')),
                ('link', models.CharField(blank=True, help_text='URL Name, Page Slug, or external link', max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('target', models.CharField(blank=True, choices=[('_self', 'Same Tab/Window (normal)'), ('_blank', 'New Tab/Window'), ('_parent', 'Parent Frame'), ('_top', 'Full Window (break frames)')], max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NavDropDownMenuConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_navdropdownmenuconfig', serialize=False, to='cms.cmsplugin')),
                ('attributes', djangocms_attributes_field.fields.AttributesField(default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_navitem', serialize=False, to='cms.cmsplugin')),
                ('dropdown', models.BooleanField(default=False)),
                ('attributes', djangocms_attributes_field.fields.AttributesField(default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NavLinkPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_navlinkpluginconfig', serialize=False, to='cms.cmsplugin')),
                ('link', models.CharField(blank=True, help_text='URL Name, Page Slug, or external link', max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('target', models.CharField(blank=True, choices=[('_self', 'Same Tab/Window (normal)'), ('_blank', 'New Tab/Window'), ('_parent', 'Parent Frame'), ('_top', 'Full Window (break frames)')], max_length=50, null=True)),
                ('dropdown', models.BooleanField(default=False)),
                ('attributes', djangocms_attributes_field.fields.AttributesField(default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NavPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_navpluginconfig', serialize=False, to='cms.cmsplugin')),
                ('style', models.CharField(blank=True, choices=[('', 'Default Nav'), ('nav-tabs', 'Tabs'), ('nav-pills', 'Pills'), ('nav-fill', 'Fill and Justify')], max_length=50, null=True)),
                ('horizontal_alignment', models.CharField(blank=True, choices=[('', 'Left Aligned'), ('justify-content-center', 'Center Aligned'), ('justify-content-end', 'Right Aligned')], max_length=50, null=True)),
                ('vertical_desktop', models.BooleanField(default=False)),
                ('vertical_mobile', models.BooleanField(default=False)),
                ('attributes', djangocms_attributes_field.fields.AttributesField(default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='HTML5Video',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_html5video', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('aspect_ratio', models.CharField(choices=[('Widescreen 16x9', '16by9'), ('Full/square Screen 4x3', '4by3')], default='Widescreen 16x9', max_length=25)),
                ('attributes', djangocms_attributes_field.fields.AttributesField(default=dict)),
                ('video_file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='html5_video_file', to='filer.file')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
