# Generated by Django 3.1.3 on 2020-11-19 18:30

from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('bootstrap4_extensions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavBarBrandPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_navbarbrandpluginconfig', serialize=False, to='cms.cmsplugin')),
                ('link', models.CharField(blank=True, help_text='URL Name, Page Slug, or external link', max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('target', models.CharField(blank=True, choices=[('_self', 'Same Tab/Window (normal)'), ('_blank', 'New Tab/Window'), ('_parent', 'Parent Frame'), ('_top', 'Full Window (break frames)')], max_length=50, null=True)),
                ('attributes', djangocms_attributes_field.fields.AttributesField(default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='NavBarPluginConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bootstrap4_extensions_navbarpluginconfig', serialize=False, to='cms.cmsplugin')),
                ('background_class', models.CharField(choices=[('bg-primary', 'Primary (blue)'), ('bg-secondary', 'Secondary (dark gray)'), ('bg-success', 'Success (green)'), ('bg-danger', 'Danger (red)'), ('bg-warning', 'Warning (yellow)'), ('bg-info', 'Info (turquoise)'), ('bg-light', 'Light (white)'), ('bg-dark', 'Dark (black)'), ('bg-transparent', 'Transparent'), ('bg-gradient-primary', 'Primary Gradient (blue)'), ('bg-gradient-secondary', 'Secondary Gradient (dark gray)'), ('bg-gradient-success', 'Success Gradient (green)'), ('bg-gradient-danger', 'Danger Gradient (red)'), ('bg-gradient-warning', 'Warning Gradient (yellow)'), ('bg-gradient-info', 'Info Gradient (turquoise)'), ('bg-gradient-light', 'Light Gradient (white)'), ('bg-gradient-dark', 'Dark Gradient (black)')], default='bg-dark', max_length=50)),
                ('background_scheme', models.CharField(choices=[('navbar-dark', 'Dark Background'), ('navbar-light', 'Light Background')], default='navbar-dark', max_length=50)),
                ('navbar_position', models.CharField(blank=True, choices=[('', 'Normal'), ('fixed-top', 'Fixed top'), ('fixed-bottom', 'Fixed bottom')], default='', max_length=50)),
                ('attributes', djangocms_attributes_field.fields.AttributesField(default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='navpluginconfig',
            name='attributes',
        ),
        migrations.AddField(
            model_name='navpluginconfig',
            name='background_class',
            field=models.CharField(choices=[('bg-primary', 'Primary (blue)'), ('bg-secondary', 'Secondary (dark gray)'), ('bg-success', 'Success (green)'), ('bg-danger', 'Danger (red)'), ('bg-warning', 'Warning (yellow)'), ('bg-info', 'Info (turquoise)'), ('bg-light', 'Light (white)'), ('bg-dark', 'Dark (black)'), ('bg-transparent', 'Transparent'), ('bg-gradient-primary', 'Primary Gradient (blue)'), ('bg-gradient-secondary', 'Secondary Gradient (dark gray)'), ('bg-gradient-success', 'Success Gradient (green)'), ('bg-gradient-danger', 'Danger Gradient (red)'), ('bg-gradient-warning', 'Warning Gradient (yellow)'), ('bg-gradient-info', 'Info Gradient (turquoise)'), ('bg-gradient-light', 'Light Gradient (white)'), ('bg-gradient-dark', 'Dark Gradient (black)')], default='bg-dark', max_length=50),
        ),
        migrations.AlterField(
            model_name='navpluginconfig',
            name='horizontal_alignment',
            field=models.CharField(choices=[('justify-content-start', 'Left Aligned'), ('justify-content-center', 'Center Aligned'), ('justify-content-end', 'Right Aligned')], default='justify-content-start', max_length=50),
        ),
        migrations.AlterField(
            model_name='navpluginconfig',
            name='style',
            field=models.CharField(blank=True, choices=[('', 'Default Nav'), ('nav-tabs', 'Tabs'), ('nav-pills', 'Pills'), ('nav-fill', 'Fill and Justify')], default='', max_length=50),
        ),
    ]
